### PR TITLE
Bump 0.11.34

### PR DESCRIPTION
**Pull request by zankia**
It's been a very long time since the last update.
I need a more recent version on my server (see ticket AUDC-1095-YHVR).

### CODE REVIEW

**Comment by zankia** [comment]
Hello,

After a week, nothing happened yet...

**Comment by Hatrix42** [comment]
We're working on it, might take some time

**Comment by zankia** [comment]
Hello again,

If you do not plan to update this repository, please mark it as inactive and stop offering gogs in scaleway...

**Comment by zankia** [comment]
no more up to date

**Pull request closed without merging**
